server:
  port: 8084

#management:
#  endpoints:
#    web:
#      exposure:
#        include: info, health, metrics  # Expose these endpoints
#  endpoint:
#    info:
#      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: root
    password: "{cipher}2e105e44ba6c2d30867ebfb177ac846d597e29f17ebdcb1c3390cb4ba3b3fb8e"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

info:
  app:
    name: "Food Service (DEV)"
    description: "Development profile , GitVersion"
#info:
#  app:
#    name: "My Spring Boot App"
#    version: "2.5.0"
#    description: "Sample application with Actuator"
